### PR TITLE
about and features

### PR DESCRIPTION
**Pull request by Leorasaharia**
I noticed that the navigation through the About and Features pages wasn't working properly in the navbar. So, I made some changes. Now, whenever someone clicks on 'About' in the navbar, they'll be directed to http://localhost:5173/about, and for 'Features', it'll be http://localhost:5173/features. Hopefully, this fixed the navigation issue.

### CODE REVIEW

**Comment by Leorasaharia** [comment]
@Mansi168 please review the PR

**Comment by Mansi168** [comment]
please mention the assigned issue!
and this branch has conflicts too, please resolve conflicts too.

i suggest update fork before doing any changes.

**Comment by Leorasaharia** [comment]
I've mentioned the issue already. I'm not able to understand what's wrong
here, not able to get what is causing the conflicts.. this is my first time
getting conflicts back.

**Review by Leorasaharia — COMMENTED** [review]
everything is too new to me, i fear im not able to solve these correctly

**Comment by Mansi168** [comment]
Conflicts occur when two people try to make changes to a file at the same time.
So, to overcome conflicts i suggest you to save your changes locally and after updating your fork, git pull and then make changes again.

**Pull request closed without merging**
