### PR TITLE
New feature quote

### PR DESCRIPTION
**Pull request by Anuhk**
## Related Issue
A new motivational quote to be displayed on the home page everyday #108
## Description
I have created a functionality which displays a new motivational quote image in every 24 hours.It is a set of 17 images which repeats itself.

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
I am attaching a video of functionality , however for demonstration purpose ,images in the video change after every one second but the actual functionality is for 24 hours. 
https://github.com/Mansi168/EmoWell/assets/145833081/e97e37c9-6b1d-4e53-995f-a1010175e323
## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
Self-review is done for 5 minutes

### CODE REVIEW

**Comment by everly-gif** [comment]
Hi @Anuhk there are issues with your code

**Comment by Anuhk** [comment]
Ok, I will try do it with the  pop up

**Comment by Anuhk** [comment]
Will be updating the PR in 2 days

**Comment by Agarwalvidu** [comment]
Please pull the request again if you will work on this. Thanks for taking your time.
@Anuhk

**Pull request closed without merging**
