### PR TITLE
feat: Animationa added in home page

### PR DESCRIPTION
**Pull request by RamakrushnaBiswal**
## Related Issue

#70 solved

## Description

animation added

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/Mansi168/EmoWell/assets/125277258/8a4f2414-cd23-440d-aabc-ba10f51752cd

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by RamakrushnaBiswal** [comment]
@everly-gif review the PR

**Review by everly-gif — APPROVED** [review]
Looks good to me @Mansi168 please proceed with final review

**Comment by RamakrushnaBiswal** [comment]
@Mansi168 please review the PR

**Comment by Mansi168** [comment]
hey, i llike your work, but your branch has conflicts, please resolve them, only then i can merge ur pr.
image

**Comment by Agarwalvidu** [comment]
@RamakrushnaBiswal I am closing this PR, please create the new one as discussed. Thank you for taking your time.

**Pull request closed without merging**
