### PR TITLE
Resolved Issue #49

### PR DESCRIPTION
**Pull request by Satuti99**
## Related Issue
Service page was not there (Issue #49)

## Description
Added a service page where this website could offer different types of services such as: Group Support, Counselling, 24/7 Customer Care. This Page is seperate so as to add to the functionality and moto of the page.  Added features like contact on whatsapp, chatbot, through email, seek support groups and much more!

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [ ] I have performed a self-review of my code
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Satuti99** [comment]
@Mansi168 Please merge the pull request

**Comment by everly-gif** [comment]
Hi @Satuti99 could you add relevant screenshots

**Comment by Satuti99** [comment]
> Hi @Satuti99 could you add relevant screenshots

Sure ma'am @Mansi168 please find attached the screenshots and video for reference.

Screenshot (190)
Screenshot (191)
https://github.com/user-attachments/assets/bec25cda-8560-4a95-9915-d804aff7880b

**Comment by Agarwalvidu** [comment]
@Satuti99 Please resolve merge conflicts!

**Comment by Mansi168** [comment]
> @Satuti99 Please resolve merge conflicts!

image

**Comment by Satuti99** [comment]
@Agarwalvidu Resolved Conflicts.

**Pull request merged**
