### PR TITLE
add:Assessment page

### PR DESCRIPTION
**Pull request by Hrishita-Paul**
Mental Health Assessment card added in feature of home page and corresponding assessment page created, #76

### CODE REVIEW

**Comment by Hrishita-Paul** [comment]
@Mansi168 ma'am, please check this pr once, I have added the mental health assessment feature and new page

**Comment by Mansi168** [comment]
I like your work, but there is a problem: the card is going out of page width. Please make its alignment within the width of the page!

**Comment by Hrishita-Paul** [comment]
@Mansi168 ma'am are you taking about the home page's cards in mobile view or the assessment page's one?

**Comment by Hrishita-Paul** [comment]
@Mansi168 ma'am please check this pr once

**Comment by Mansi168** [comment]
> @Mansi168 ma'am please check this pr once

Still the same problem exists.

**Comment by Hrishita-Paul** [comment]
I am not able to understand in which page does the error persists, home page or the assessment page and in which device? Could you please let me know once, on my side it is working in mobile view too and the cards are not going out of page width

**Comment by Mansi168** [comment]
I was talking about this...
image

**Comment by Hrishita-Paul** [comment]
This is how it looks on my end , checked now also 
image

**Comment by everly-gif** [comment]
@Mansi168 this has been fixed with other PRs targetting navbar UI

> I was talking about this... image

**Comment by Mansi168** [comment]
please resolve conflicts, so that i can merge it @Hrishita-Paul .
image

**Comment by Hrishita-Paul** [comment]
@Mansi168 I have resolved the conflicts and the cards are aligned within the page width in the mobile view and the website view.

**Comment by Agarwalvidu** [comment]
@Mansi168 Authorization on vercel is needed, rest things are working fine.

**Pull request merged**
