### PR TITLE
Fixed Footer Links Scroll to Top of Page Upon Click 

### LINKED ISSUE #296: 🐞[Bug]: Footer Links Do Not Scroll to Top of Page Upon Click
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @everly-gif @Mansi168 and @Agarwalvidu 

When clicking on the links in the footer, the page does not automatically scroll to the top. Instead, users need to manually scroll up to view the content. This behavior affects user experience and navigation efficiency.

### Add ScreenShots

https://github.com/user-attachments/assets/fd0eea54-86d5-4bed-9ffd-86fdbe5d210d

Upon clicking any link in the footer, the page should smoothly scroll to the top, displaying the relevant section without requiring manual scrolling.

I would like to fix it, coul+d you please assign this issue to me?

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by MastanSayyad**
## Description

Hey @Mansi168, @everly-gif and @Agarwalvidu 

- issue fixes #296

I have fixed the issue:

- Footer Links Scroll to the Top of the Page Upon Click
- Update `handleClick` to `navigate` to the home page first, and then scroll to the top or to the specific section after a short delay.
- Updated `FooterLink` components, Pass the section ID to `handleClick` where necessary.

https://github.com/user-attachments/assets/4b788d2a-731e-4cfb-9a56-310eeff74c59

## Type of PR

- [x] Bug fix

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Agarwalvidu** [comment]
Hey @MastanSayyad 
Please remove commits for alignment and responsiveness please as it is already assigned to someone else. Sorry for the inconvenience we appreciate your extra work, but please work only on the assigned issue as it creates fuss for us, alignment and responsiveness issue is already assigned to some other contributors!

We highly appreciate your footer links scroll to up using handle click and navigate.
Hope you understand!
Thank you!

**Comment by Agarwalvidu** [comment]
@MastanSayyad 
Also please revert your changes in package.json and package-lock.json files.

**Comment by MastanSayyad** [comment]
@Agarwalvidu Done all the changes, extremely sorry for the oversight! I'll keep this mind

**Comment by Agarwalvidu** [comment]
Great! No worries!
Your PR will be merged by tomorrow!
Thank you for collaborating!

**Pull request merged**
