### PR TITLE
Reading Section Enhancement

### PR DESCRIPTION
**Pull request by PriyamvadaShah**
## Related Issue
Reading Section Enhancement

## Description
Added sub sections, footer, search functionality and toggle button.

## Screenshots
Screenshot 2024-07-15 005711
Screenshot 2024-07-15 005649
Screenshot 2024-07-15 005640
Screenshot 2024-07-15 005628
Screenshot 2024-07-15 005613
Screenshot 2024-07-15 005600

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [x] Documentation update
- [x] Other (specify): _______________

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
GSSoC'24

### CODE REVIEW

**Comment by Agarwalvidu** [comment]
@PriyamvadaShah 
Please add valid screenshots to your work.

**Comment by PriyamvadaShah** [comment]
> @PriyamvadaShah Please add valid screenshots to your work.

Done

**Comment by Agarwalvidu** [comment]
@PriyamvadaShah 
Can you please do one thing, sync your fork and clone the repo again and then again do the required changes. Then raise a new PR. Currently there is something that shouldn't be there in the changes files.
Also make sure to enhance the reading section only.

**Comment by Agarwalvidu** [comment]
@PriyamvadaShah 
Please reply asap.

**Comment by PriyamvadaShah** [comment]
> @PriyamvadaShah Please reply asap.

Yeah sure, doing it.

**Pull request closed without merging**
