### PR TITLE
Service Page #49

### PR DESCRIPTION
**Pull request by Satuti99**
Added a service page where this website could offer different types of services such as: Group Support, Counselling, 24/7 Customer Care. This Page is  seperate so as to add to the functionality and moto of the page.

Added features like contact on whatsapp, chatbot, through email, seek support groups and much more!

## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [ ] I have performed a self-review of my code
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by Satuti99** [comment]
@Mansi168 Respected ma'am please review and merge the PR

**Comment by Mansi168** [comment]
plz resolve conflicts

**Comment by Satuti99** [comment]
@Mansi168 Resolved the conflict in src/App.jsx. Please Check.

**Comment by Satuti99** [comment]
> @Mansi168 Resolved the conflict in src/App.jsx. Please Check.

Respected ma'am please check the updates  so that i can proceed with another issue (#199) assigned to me

**Comment by Mansi168** [comment]
See, your branch still has conflicts.
image

do one thing, save your work locally, again clone the repo and then made the changes.

**Pull request closed without merging**
