### PR TITLE
ui changes, responsivesness

### PR DESCRIPTION
**Pull request by Leorasaharia**
made the about page responsive as i noticed for mobile devices (small devices) the texts were overlayed with the "our features" page. also made changes to the ui of Register button and made minute responsive changes to navbar elements

### CODE REVIEW

**Comment by Mansi168** [comment]
hey, please mention the issue number here!

**Comment by Leorasaharia** [comment]
#26

**Comment by Leorasaharia** [comment]
@Mansi168

**Comment by Leorasaharia** [comment]
resolved conflicts

**Comment by Leorasaharia** [comment]
@Mansi All the issues mentioned in #26 have been resolved. In this new commit, I have added a hover effect to the text on the home page (Hero.jsx) and implemented smooth scrolling for swift navigation. Please review the pr, thankyou

**Comment by Leorasaharia** [comment]
@Mansi168

**Comment by everly-gif** [comment]
Could you please fix the conflicts

**Comment by everly-gif** [comment]
@Mansi168 pls review

**Comment by Agarwalvidu** [comment]
@Leorasaharia your commit contains merge conflicts please resolve these.

**Comment by Leorasaharia** [comment]
there are no conflicts, I already resolved them so many times.

**Comment by Agarwalvidu** [comment]
Screenshot 2024-07-13 163540
Please check here!

**Comment by Agarwalvidu** [comment]
@Leorasaharia What you can do is sync your fork and fetch the changes then raise the PR again. Please let me know if you are able to work on resolving conflicts by this method.

**Pull request closed without merging**
