### PR TITLE
Features misalignment of buttons and pictures.

### LINKED ISSUE #23: Buttons misaligned in feature cards
1. Alignment Issue: Buttons Not Aligned Horizontally
2. Button Alignment Problem in ‘Our Features’ Section
Screenshot 2024-05-09 221208

### PR DESCRIPTION
**Pull request by MahawarHemlata**
Fixed Issue

closes #23 

Hi, I am feeling happy to inform you that issue that I've created is fixed successfully. this is my first open source contribution so if i've done any mistake please forgive me.
Screenshot 2024-05-10 130315

### CODE REVIEW

**Comment by MahawarHemlata** [comment]
and yeah Could you please review my contribution and provide feedback on any errors or improvements that need to be made? I'm eager to learn and ensure that my contributions align with the project's standards and goals.

**Comment by MahawarHemlata** [comment]
Fixes Issue
closes #23 
Screenshot 2024-05-10 130315

Note to reviewers

I have pushed the changes of #23 here.
@Mansi168 please review.

**Comment by MahawarHemlata** [comment]
really sorry for messing things up. actually I'm a beginner in open source contribution so please forgive me.

**Comment by Mansi168** [comment]
Hey, you have done features correctly, but there is an issue with the CSS that you have changed in src/index.css for the img tag. It is also making changes in the logo of the navbar. To avoid that, please use a different tag name for either of the images to avoid this problem. 
image

**Comment by MahawarHemlata** [comment]
@Mansi168  ohk thanks for informing me

**Comment by MahawarHemlata** [comment]
Can you please check it now. actually i've made those changes in the same branch.
@Mansi168

**Pull request merged**
