### PR TITLE
#67 Reading Section Enhancement

### PR DESCRIPTION
**Pull request by PriyamvadaShah**
## Related Issue
#67 Working on the Reading Section

## Description
-Implemented different sub-sections for various different mental disorders
-Search functionality for each section using pre-made tags
-Added Footer
-Implemented Dark Mode feature for the page to help users change preferences

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

Screenshot 2024-06-08 182711
Screenshot 2024-06-08 182656

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
Through GSSoC'24

### CODE REVIEW

**Comment by Mansi168** [comment]
hey, i dont like this huge button for  mode  switching..
image

Apert from this, the subheadings for particular reading section needs some enhancement like boldness and increment in size.

**Comment by PriyamvadaShah** [comment]
> hey, i dont like this huge button for mode switching.. image
> 
> Apert from this, the subheadings for particular reading section needs some enhancement like boldness and increment in size.

Ok I will make the change accordingly and send you.

**Comment by PriyamvadaShah** [comment]
> hey, i dont like this huge button for mode switching.. image
> 
> Apert from this, the subheadings for particular reading section needs some enhancement like boldness and increment in size.

Hi! I have done all the required changes and also ensured responsiveness of the page. Also removed the extra horizontal scroll that was happening on all pages. Check it out. Thank you.

**Review by everly-gif — COMMENTED** [review]
Hi, just tweak the UI a little.
1) Im seeing alignment issues of search bar, it isnt center
2)  the dark button too, it only switches after a double click. the sun image and background and the background color keep it as white(same color) so it looks better.

Functionality wise looks great

**Comment by PriyamvadaShah** [comment]
> Hi, just tweak the UI a little.
> 
> 1. Im seeing alignment issues of search bar, it isnt center
> 2. the dark button too, it only switches after a double click. the sun image and background color keep it as white(same color) so it looks better.
> 
> Functionality wise looks great

Hey I've changed it according to what you mentioned. Please see to it. Thanks.

**Comment by PriyamvadaShah** [comment]
@everly-gif Please review.

**Comment by Agarwalvidu** [comment]
@PriyamvadaShah  Your PR has merge conflicts Please resolve it.

**Comment by everly-gif** [comment]
@PriyamvadaShah , Just pulled your changes to see you work, it looks great ! Great job. Just fix the conflict, from my side its good to go 

> @everly-gif Please review.

**Review by everly-gif — APPROVED** [review]

**Comment by Agarwalvidu** [comment]
@PriyamvadaShah 
Please confirm your availability to resolve the conflicts as soon as possible.

**Comment by PriyamvadaShah** [comment]
> @PriyamvadaShah Please confirm your availability to resolve the conflicts as soon as possible.

Yes I;m fixing the conflicts and will inform you after it ASAP.

**Pull request closed without merging**
