### PR TITLE
fixed footer #345

### LINKED ISSUE #345: [Bug]: contact page css in mobile view
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

contact page is not responsive

### Add ScreenShots

image

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by dhairyagothi**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
closes #345 
## Description
[Please include a brief description of the changes or features added]
fixed 
image

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [ ] I have performed a self-review of my code
- [ ] I have read and followed the Contribution Guidelines.
- [ ] I have tested the changes thoroughly before submitting this pull request.
- [ ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by dhairyagothi** [comment]
@Mansi168 please check and merge

**Comment by dhairyagothi** [comment]
@everly-gif please merge PR

**Comment by everly-gif** [comment]
Hi, in the #345 you claimed to fix the contact page responsiveness. Did you? As I can only see footer changes.

**Comment by dhairyagothi** [comment]
yes i have fixed that only due to width of continer in footer the page in unresponsive @everly-gif

**Comment by everly-gif** [comment]
Got it thanks for clarifying

**Review by everly-gif — APPROVED** [review]
@Mansi168

**Comment by dhairyagothi** [comment]
pleasse add gssoc label @everly-gif and level badge

**Comment by everly-gif** [comment]
> pleasse add gssoc label @everly-gif and level badge

Done

**Pull request merged**
