### PR TITLE
responsive-changes

### PR DESCRIPTION
**Pull request by Che140401**
Changes in responsiveness to mobile width 360px

### CODE REVIEW

**Comment by Mansi168** [comment]
hy, it seems good but you need to make some changes. 
1. decrease width of navbar
2. about section overlapping with home section
3. decrease size of cards in features and team pages
image

**Comment by Mansi168** [comment]
please make sure to run git pull before making any changes.

**Comment by Mansi168** [comment]
Hey @Che140401  are you working on it? or i close this pr?

**Comment by K123Ritesh** [comment]
@Che140401 resolve the conflicts man...

**Comment by everly-gif** [comment]
@Che140401 
This PR has review comments from the maintainer , please address them.
If you face any issues in doing so, contact me or the maintainer via discord.
Due to the time taken for the resolvation of this issue, we need a response ASAP, possibly by tomorrow . Otherwise this issue will be assigned to the next interested assignee.

**Comment by everly-gif** [comment]
No update, closing the PR

**Pull request closed without merging**
