### PR TITLE
Issue #277

### PR DESCRIPTION
**Pull request by Ayush-may**
#277 
## Related Issue
None

## Description
- Added indentation for better readability
- Added some extra css 
- Added responsive design to the image 
- Added  some extra divs
- and many more 😫 

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

After 

image

image

image

image

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
There is issue with navbar , i didnt work much in navbar issue becoz this issue isnt about that , so i will work on it in next issue

### CODE REVIEW

**Comment by Agarwalvidu** [comment]
@Ayush-may 
Please revert your changes in Navbar as some other issue related to Navbar was already it will create merge conflicts!

**Comment by Ayush-may** [comment]
@Agarwalvidu I reset the navbar designs , u can check now

image

**Comment by Agarwalvidu** [comment]
Cool!

**Comment by Agarwalvidu** [comment]
@Ayush-may Please resolve the conflicts and also please revert the changes done in Healthy Minds Happy Life text. Or if possible try any other ideas for it.

**Comment by Ayush-may** [comment]
> @Ayush-may Please resolve the conflicts and also please revert the changes done in Healthy Minds Happy Life text. Or if possible try any other ideas for it.

@Agarwalvidu  Merge conflict is resolved 
and why to revert the changes in that text , Do u want me to revert font family or fully revert of that text ??

the previous text design had too much css which had no use so i removed some but later I face responsive issue, so i did this too.

If u want to revert the font family then i can do this 
thanks

**Comment by Ayush-may** [comment]
I revert the changes in text

image

**Comment by Agarwalvidu** [comment]
Okay Thanks!

**Pull request merged**
