### PR TITLE
✔️Completely Enhanced the UI of Review Page!

### LINKED ISSUE #263: ➕Feature: Implement "Feedback Page" to EmoWell Website
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @Mansi168, @everly-gif and @Agarwalvidu 

I want to implement a "Feedback form/page" on the EmoWell website to gather user feedback and improve the Website services. 
The feedback form page **should be accessible from the main navigation** and allow users **to easily provide their thoughts and suggestions.**

### Here's What Will I Do 
- Form Fields **(Name, email, Rating, Feedback)**
- I Will **Add a "Modal" Button** On Clicking which the **Feedback Page will open** (for ex below)
- Additionally, will add a "Tooltip" for the modal feedback button.
- Will Ensure that **email field contains a valid email address.**
- **"Star Rating System" that must be between 1 and 5.**
- **The form will match the current website's design and aesthetics.**
- Provide a **thank you alert upon successful submission.**

**Here's Example of My Previous Work -**

https://github.com/user-attachments/assets/8105c34e-5dd0-4b8e-a2ea-b9d19ce8c66d

### Use Case

Emowell aims to empower individuals in managing their emotional wellbeing effectively through its diverse features. 
**By integrating a feedback form, we can directly capture user insights and preferences.**

Please assign me this issue under GSSoC'24

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by aslams2020**
Hey @Mansi168 , @everly-gif and @Agarwalvidu 
issue closes #263 

I have implemented the necessary changes with the already existing "Review" Form Page

### Here's What I Did -
1. I Have **Completely Enhanced the Alignment and Styling** of the Review form
2. **Added "Star-Rating" System** for it
3. Also, I have **added the "DropDown" Functionality to give users Default Feedback** Texts and Also an "Other" Option
4. **Tried my best to follow the website theme.**
5. **Made it "Responsive"** across all screen sizes.
6. **Implemented reset functionality** for the form.
7. **Added an alert for successful submission.**

**Here's the Complete Implementation -**

https://github.com/user-attachments/assets/59ad4bb3-f9a3-45df-926f-f403a9bc8e97

Please take a look and review it.

## Type of PR
- [x] Feature enhancement

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by Mansi168** [comment]
please resolve conflicts
image

**Comment by aslams2020** [comment]
@Mansi168 @everly-gif Done!.. Please check

**Comment by everly-gif** [comment]
@Mansi168

**Review by everly-gif — APPROVED** [review]

**Comment by aslams2020** [comment]
@Mansi168

**Comment by aslams2020** [comment]
@Mansi168

**Comment by aslams2020** [comment]
@everly-gif please add labels

**Pull request merged**
