### PR TITLE
Footer dialer feature added

### PR DESCRIPTION
**Pull request by pankaj-bind**
## Related Issue
Issue number #59 Footer dialer feature

## Description
Now when user clicks on phone number it will redirects them to phone dialer pad.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

https://github.com/Mansi168/EmoWell/assets/73558583/3b9318cf-4340-45d7-8f2c-4c6c6740ebcb

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Review by everly-gif — APPROVED** [review]

**Comment by everly-gif** [comment]
Looks good @pankaj-bind , @Mansi168 pls proceed with final review

**Comment by pankaj-bind** [comment]
would you please merge this PR

**Comment by Mansi168** [comment]
hey, i like ur work, but plz resolve conflicts.
image

**Comment by Agarwalvidu** [comment]
@pankaj-bind please confirm your availability to work on the conflicts otherwise we will close your PR.

**Comment by pankaj-bind** [comment]
ok, I'll do it.

**Pull request closed without merging**
