### PR TITLE
Update Reading Area

### PR DESCRIPTION
**Pull request by PriyamvadaShah**
## Related Issue
Enhancing the Reading Area

## Description
Adding sub-sections, dark mode, footer and search functionality enhancement in reading section.

## Type of PR

- [x] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
Screenshot 2024-07-15 005711
Screenshot 2024-07-15 005628
Screenshot 2024-07-15 005613
Screenshot 2024-07-15 005600
Screenshot 2024-07-15 005649Screenshot 2024-07-15 005640

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [ ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
GSSoC'24

### CODE REVIEW

**Comment by PriyamvadaShah** [comment]
I have only updated Reading Area added one toggle button folder, another ReadingAreaElements file and added data for the sub-sections. 
The only think I had to change other than this was package.json because it had two axios dependencies and hence the file was not running on vite.

**Comment by Agarwalvidu** [comment]
It is showing 10 files changed.

**Comment by PriyamvadaShah** [comment]
> It is showing 10 files changed.

Yes there are 4 data files for sub-sections itself, 2 are package and package-lock, 2 are toggle button files, one for readingAreaElements and one for Reading Area.

**Comment by Agarwalvidu** [comment]
As no update is shown by the contributor, I am closing this PR. If incase you still wanna work on this. Please tag me I will reopen this.

**Pull request closed without merging**
