### PR TITLE
fix: taking extra space

### LINKED ISSUE #69: The page is not responsive along width taking extra width
In the ``main-page`` when we set the page we can see the unresponsiveness of the page along width.
We can fix this by setting the width to 100 vw or else we can consider other methods

[cinnamon-2024-05-12T192702+0530.webm](https://github.com/Mansi168/EmoWell/assets/116784047/712d36c7-6120-44f1-80a4-730a950836f1)

You can see the issue by clicking the video

### PR DESCRIPTION
**Pull request by upsaurav12**
fixes #69 
I have fixed the extra space but there is problem that the button is not visible between 1017px to 768px 
image
we can fix this by changing the button's ``position`` towards left and their ``size`` .
So i want to ask you should go to solve this problem with this approach??

### CODE REVIEW

**Comment by upsaurav12** [comment]
Hi @Mansi168 we can do one more thing 
that we can change breakpoint from ``768px`` to ``1030px`` it will look like this
[cinnamon-2024-05-13T125427+0530.webm](https://github.com/Mansi168/EmoWell/assets/116784047/0567715d-ad47-40d7-9700-a57e07c374bf)

**Comment by upsaurav12** [comment]
Hi @Mansi168 Pls review this

**Comment by Mansi168** [comment]
Hey, have you updated your fork before committing? As there is some problem with your branch, it has not been deployed.

**Comment by upsaurav12** [comment]
I dont know what happened but i remember that there was a merge conflit so i think that is the cause

**Comment by Mansi168** [comment]
merge conflict occured bcz you made changes in a file before pulling changes, thats why asking if you had updated the fork!

now, just save your changes in local and pull changes and then do your changes and then commmit.

**Comment by upsaurav12** [comment]
Hi @Mansi168 i have commited changes and looks like this commit does'nt have any conflicts

**Comment by everly-gif** [comment]
@upsaurav12 you do have conflicts, please resolve them.

**Comment by everly-gif** [comment]
Closing due to no response.

**Pull request closed without merging**
