### PR TITLE
✔️Fixed Navbar and Resolved Multiple ProgressBar Issue !

### LINKED ISSUE #373: BUG🐞: Multiple Scroll Progress Bars Appearing on Scroll
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @Mansi168 , @everly-gif and @Agarwalvidu ,

I have **encountered a Bug** where **multiple scroll progress bars appear at the top of the page upon scrolling.** 

This results **in three progress bars covering the navbar,** which **negatively impacts the user experience** and visual aesthetics. **There should be only one scroll progress bar at the top of the navbar.**

ISSUE : 

https://github.com/user-attachments/assets/bd4712a0-c408-400c-9de0-b4601b0598f8

### **Here are the details:**
**Expected Behavior:** Only one scroll progress bar should be visible at the top of the navbar
**Actual Behavior:** Three progress bars appear, overlapping and covering the navbar

Please look into this issue and please assign me.
Thank you!

### Add ScreenShots

_No response_

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by aslams2020**
Hey @everly-gif @Mansi168 
@Agarwalvidu 
issue closes #373 

- I have **fixed the Navbar Elements visibility** issue 
- **Resolved the issue of Multiple ScrollProgress** bar in the navbar.

Please take a look - 

https://github.com/user-attachments/assets/c4bade82-20f1-4e1b-b077-064ca6d313e2

@everly-gif Earlier, The Navbar Elements were not visible. 

Thankyou! 

## Type of PR

- [x] Bug fix

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by aslams2020** [comment]
@Mansi168 @everly-gif Please review it

**Comment by aslams2020** [comment]
@everly-gif @Mansi168 Please take a look

**Review by everly-gif — APPROVED** [review]

**Comment by everly-gif** [comment]
@Mansi168

**Comment by aslams2020** [comment]
@Mansi168 please review it

**Comment by aslams2020** [comment]
@Mansi168

**Comment by Mansi168** [comment]
plz resolve conflicts
image

**Comment by aslams2020** [comment]
@Mansi168 Resolving it!

**Comment by aslams2020** [comment]
@Mansi168 Done! PLease review it

**Comment by aslams2020** [comment]
@Mansi168

**Comment by aslams2020** [comment]
@Mansi168 Please merge the PR

**Comment by aslams2020** [comment]
@Mansi168 Please merge the PR with LABELS.
Today the GSSOC is going to end...So that I can get my points of this on the leaderboard before that

**Comment by aslams2020** [comment]
@everly-gif Please give lables

**Comment by aslams2020** [comment]
@Mansi168 Please merge the PR.
else Should I make PR in the new repo made for merging the unmerged PRs

**Comment by aslams2020** [comment]
@Mansi168

**Pull request closed without merging**
