### PR TITLE
Added Animated icon to footer

### PR DESCRIPTION
**Pull request by SadafKausar2025**
## Related Issue #103 
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

## Description
[Please include a brief description of the changes or features added]

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)
https://github.com/Mansi168/EmoWell/assets/137484958/3d0921cf-9574-425c-84b6-4678cef9daa4
[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
hello @everly-gif 
please review this PR and merge it

**Comment by SadafKausar2025** [comment]
hello @Mansi168 
please review this PR and merge it

**Comment by Mansi168** [comment]
plz resolve conflicts

**Comment by SadafKausar2025** [comment]
hello @Mansi168 
I have resolved the conflict . please merge it

**Comment by SadafKausar2025** [comment]
please also give level after merging

**Comment by SadafKausar2025** [comment]
hello @Mansi168 
please merge it and give level also

**Comment by Mansi168** [comment]
thanks for the pr.

**Comment by SadafKausar2025** [comment]
> thanks for the pr.

Hello @Mansi168 
Please add levels also

**Pull request merged**
