### PR TITLE
issue #306

### PR DESCRIPTION
**Pull request by Ayush-may**
#306 
## Related Issue
None

## Description
- change privacy page contents

## Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / videos (if applicable)

image

image

image

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

Pls add level before merging 🥲

### CODE REVIEW

**Comment by Agarwalvidu** [comment]
Please make the color theme according to the website also please change that cross to plus icon.

**Comment by Ayush-may** [comment]
> Please make the color theme according to the website also please change that cross to plus icon.

@Agarwalvidu Now looks good ?

image

**Comment by Agarwalvidu** [comment]
Looks good to me!
@Mansi168 Have a look and merge it!

**Comment by Ayush-may** [comment]
> Looks good to me!
> @Mansi168 Have a look and merge it!

Done ?

**Pull request merged**
