### PR TITLE
Added The Scroll to Top Button in Each Pages

### LINKED ISSUE #322: BUG: The Scroll to Top Button is Only Present in Home Page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @Mansi168, @everly-gif and @Agarwalvidu 

On this website, the scroll to the top is only present on home page not on other pages.

image

image

Could you please assign this issue to me under GSSOC24?

### Add ScreenShots

_No response_

### What browsers are you seeing the problem on?

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by RadhikaMalpani1702**
## Description
Hey @Mansi168, @everly-gif and @Agarwalvidu 

- issue closes #322 

I have added the scroll to top button in each pages

https://github.com/user-attachments/assets/5c61d04b-e58c-42ff-a684-d9f23ba38283

## Type of PR

- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Checklist:
- [X] I have performed a self-review of my code
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by RadhikaMalpani1702** [comment]
@Mansi168 Please merge this PR

**Comment by Mansi168** [comment]
please resolve conflicts,

**Comment by RadhikaMalpani1702** [comment]
@Mansi168 I have resolved the conflicts

**Comment by RadhikaMalpani1702** [comment]
@Mansi168 Please merge this PR

**Comment by everly-gif** [comment]
Please resolve conflicts @RadhikaMalpani1702

**Comment by RadhikaMalpani1702** [comment]
@Mansi168 I have resolved the conflicts

**Comment by RadhikaMalpani1702** [comment]
@Mansi168 @everly-gif @Agarwalvidu Please merge this PR as the GSSOC is near to it's end

**Comment by RadhikaMalpani1702** [comment]
@Agarwalvidu Please add the levels

**Pull request merged**
