### PR TITLE
Added "Scroll Down Progress Bar" Across The Website

### LINKED ISSUE #311: [Feature Request]: Add Scroll Down Progress Bar Matching to Website Design Theme
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @Agarwalvidu, @everly-gif and @man

I would like to suggest adding a scroll down progress bar to the website to enhance user experience. 

like this

image

### Use Case

- A scroll progress bar visually indicates how much of the page has been scrolled and how much is left, providing users with a better sense of their position on the page. 
- This feature can be especially helpful for long pages blogs, docs, and articles.

### Benefits

- Enhances user experience by providing visual feedback.
- Useful for long pages or articles.
- Improves overall navigation and user satisfaction
- Looks more engaging.

### Priority

High

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by MastanSayyad**
## Related Issue
- Issue Fixes #311 

## Description

Hey @everly-gif , @Mansi168 and @Agarwalvidu 

I have added Scroll down progress bar matching the website design theme and also I have ensure it is present across all pages

image

https://github.com/user-attachments/assets/78bb7966-0f03-42bf-afd2-c157a1cfed39

## Type of PR

- [x] Feature enhancement

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by MastanSayyad** [comment]
Hey @everly-gif , @Mansi168 please review it

**Comment by Mansi168** [comment]
> Hey @everly-gif , @Mansi168 please review it

hey, please add scroll bar at bottom of the website.

**Comment by MastanSayyad** [comment]
> > Hey @everly-gif , @Mansi168 please review it
> 
> hey, please add scroll bar at bottom of the website.

It is usually present at the top of the page only, It is not horizontal scroll bar, it is Scroll down **progress** bar which shows the progress of how much the page is remained as we go down!  @Mansi168

**Comment by MastanSayyad** [comment]
@everly-gif , @Mansi168 please merge it!

**Comment by everly-gif** [comment]
I think @Mansi168 meand bottom of the navbar. If not , I think that's a good place for it

**Comment by MastanSayyad** [comment]
> I think @Mansi168 meant bottom of the navbar. If not , I think that's a good place for it

Yes, The progress bar usually appears on the top of the page above navbar

**Pull request merged**
